### ISSUE TITLE
Is there a method that allows access to files contained in a forensic image directly?

### ISSUE THREAD

**Issue by ajama-1984** [jarlethorsen/diskimage#2]
Hi,

Are there methods that allow access to files contained in the image directly?
 At the moment the documentation just allows the listing of items. Is there a way to pass/access each file stored in a partition on an E01 image?

**Comment by jarlethorsen** [comment]
Hi.

Once you have an **Item** object
https://github.com/jarlethorsen/diskimage/blob/f5fcefa75e669466a234053397a7f6b436ae51e8/diskimage/item.py#L5-L17

for example by using the get_items() method
https://github.com/jarlethorsen/diskimage/blob/f5fcefa75e669466a234053397a7f6b436ae51e8/diskimage/filesystem.py#L63-L74

Each Item has an `open()` method that will give you a file handle to the actual file.
https://github.com/jarlethorsen/diskimage/blob/f5fcefa75e669466a234053397a7f6b436ae51e8/diskimage/item.py#L54-L62

The handle is of type **ExtPytskFile** (an extended version of `pytsk3.File`) and you have the following methods available
https://github.com/jarlethorsen/diskimage/blob/f5fcefa75e669466a234053397a7f6b436ae51e8/diskimage/filesystem.py#L258-L311


A method showing how to extract multiple files is shown in
https://github.com/jarlethorsen/diskimage/blob/f5fcefa75e669466a234053397a7f6b436ae51e8/diskimage/filesystem.py#L214-L255

I'm closing this issue, but feel free to re-open if this did not answer your question.
